### ISSUE TITLE
Unresolved external symbol VariantToFlexbuffer

### ISSUE THREAD

**Issue by TricksterGit** [firebase/firebase-cpp-sdk#190] opened 2020-11-17 12:57 UTC
Hi,
I have similar problem as in #162 and #189: when building it on Windows with VS2017 (environment msvc_x64_x86). I am using version 6.16.1.

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\firebase_database.lib(3a24efa24aa752e49ffc1576757b342b_database.dir_Debug_level_db_persistence_storage_engine.obj) : error LNK2019: unresolved external symbol "bool __cdecl firebase::util::VariantToFlexbuffer(class firebase::Variant const &,class flexbuffers::Builder *)" (?VariantToFlexbuffer@util@firebase@@YA_NAEBVVariant@2@PEAVBuilder@flexbuffers@@@Z) referenced in function "public: bool __cdecl <lambda_e4f0c2f9cb695facf4fbcf828e4775a5>::operator()(class std::vector<unsigned char,class std::allocator<unsigned char> > *)const " (??R<lambda_e4f0c2f9cb695facf4fbcf828e4775a5>@@QEBA_NPEAV?$vector@EV?$allocator@E@std@@@std@@@Z)
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\ResultsHandlerLib\ResultsHandlerLib.dll : fatal error LNK1120: 1 unresolved externals
```

Some more info about my build configuration (CMake):
```
set(MSVC_RUNTIME_MODE MD)
set(ADDITIONAL_LIBS advapi32 ws2_32 crypt32 iphlpapi psapi userenv rpcrt4 ole32 shell32)

SET(FIREBASE_CPP_SDK_DIR "${CMAKE_CURRENT_SOURCE_DIR}/../firebase_cpp_sdk")
add_subdirectory(${FIREBASE_CPP_SDK_DIR} bin/ EXCLUDE_FROM_ALL)
set(firebase_libs firebase_auth firebase_database firebase_firestore firebase_app)
```

_Originally posted by @TricksterGit in https://github.com/firebase/firebase-cpp-sdk/issues/162#issuecomment-728329769_

**Comment by chkuang-g** [comment] 2020-11-24 19:58
Duplicate of #189

**Closed by chkuang-g** 2020-11-24 19:58 UTC
Labels: api: core, new
