### ISSUE TITLE
[Bug] App crash when user home folder contains non latin characters

### ISSUE THREAD

**Issue by awemvfx** [firebase/firebase-cpp-sdk#728] opened 2021-11-03 14:28 UTC
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) 
  * Firebase C++ SDK version: 8.6.0
  * Problematic Firebase Component: firestore
  * Other Firebase Components in use: auth
  * Platform you are using the C++ SDK on: Windows
  * Platform you are targeting: desktop

### [REQUIRED] Please describe the issue here:

(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

#### Steps to reproduce:

Create user system account with **NON LATIN** characters in name eg. björn
User system home path looks like: "C:\Users\björn\AppData\Local"

1. App init is ok
2. Create user account is ok
3. Listen some collection crash app instantly with error code -529697949

"C:\Users\björn\AppData\Local\firestore" is created but there is no files inside only empty directories
"C:\Users\björn\AppData\Local\firebase-heartbeat" is NOT created

What's the issue repro rate? 100%

**Comment by schmidt-sebastian** [comment] 2021-11-03 20:30
Thanks for reporting this. I will look into this and see if I can reproduce this behavior.

**Comment by dawidpietrasina** [comment] 2021-11-17 08:53
Any update for this issue ?

**Comment by wu-hui** [comment] 2021-11-18 19:43
This is a bit hard to reproduce actually, since my corp laptops always use my username, which does not contain non-ascii chars.

Is it possible for you to extract any logs, stack traces? Can you try turn on Firestore debug logging as well?

**Comment by dconeybe** [comment] 2021-12-02 21:16
FYI This may be the same root cause but surfacing in the Unity SDK: https://github.com/firebase/quickstart-unity/issues/1196

**Comment by dconeybe** [comment] 2022-03-15 20:26
I've done some investigation and I've found the root cause, but I'm not sure how to fix it.

The crash happens when opening the LevelDb database in [`firestore_client.cc`](https://github.com/firebase/firebase-ios-sdk/blob/33a74677484a5877f5be472fbb0ade7b0c7612fa/Firestore/core/src/core/firestore_client.cc#L191-L198). It ultimately calls down to LevelDb's [`WindowsEnv::CreateDir()`](https://github.com/google/leveldb/blob/4fb146810cd265ffefa7f9905c016ae965ad36c8/util/env_windows.cc#L531-L536) which uses the Windows API function [`CreateDirectoryA()`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createdirectorya) to create the directory.

The problem is that `CreateDirectoryA()` is the "ANSI" version of the function and can only handle ASCII characters; therefore, this function fails when invoked with non-ASCII characters, such as `ö`.

At one point there was an attempt to instead use [`CreateDirectoryW()`](https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-createdirectoryw), the "wide character" companion to `CreateDirectoryA()`, but that effort appears to have been abandoned: https://github.com/google/leveldb/issues/519.

One interesting comment in that issue is this https://github.com/google/leveldb/issues/519#issuecomment-337366812, which suggests

> ...following the approach taken by Chromium's LevelDB integration. Chromium builds (and runs) on Windows, and does not require modifications to the rest of the LevelDB.

**Comment by Girildo** [comment] 2022-05-09 08:20
Any news/progress on this issue? Living in German-speaking country this issue is quite painful for us.

**Comment by dconeybe** [comment] 2023-06-01 20:37
This bug is fixed in v11.1.0 (https://firebase.google.com/support/release-notes/cpp-relnotes#version_1110_-_may_31_2023). Please try it out!

**Closed by dconeybe** 2023-06-01 20:37 UTC
Labels: api: firestore, type: bug
