### ISSUE TITLE
Switch to python3

### ISSUE THREAD

**Issue by lnjX** [firebase/firebase-cpp-sdk#48] opened 2020-03-27 19:21 UTC
https://github.com/firebase/firebase-cpp-sdk#prerequisites requires Python2. Python2 is deprecated and has run out of support. It's not available on my system anymore (debian bullseye). Please switch to python3 which also has abseil-py and protobuf available.

**Comment by patm1987** [comment] 2020-06-17 20:01
Hi @lnjX ,

Checking in with the team, it should work in Python 3 on Linux (and MacOS). There does seem to be a Windows related issue that they know about.

Were you unable to build?

**Comment by lnjX** [comment] 2020-06-20 11:25
Ah ok, thank you. I think the problem was that it prefers python 2.x on debian/ubuntu because the scripts use the "python" command, which is python 2 on debian (but python 3 on archlinux e.g.). I still had a simple python 2 binary installed, but I removed that completely from my system now and created a symlink from `python` to `python3` and this works for me now.

**Comment by wakely** [comment] 2020-06-21 00:11
It will not build for me on CentOS8 when python points to python3, but will build when it points to python2.  This is tested with a fresh docker image (both 8.1.1911 and 8.2.2004).  The problem is in nanopb:
````
         ********************************************************************
         *** Failed to import the protocol definitions for generator.     ***
         *** You have to run 'make' in the nanopb/generator/proto folder. ***
         ********************************************************************
    
Traceback (most recent call last):
  File "/firebase-cpp-sdk/build/external/src/firestore/Firestore/Protos/nanopb_cpp_generator.py", line 25, in <module>
    import nanopb_generator as nanopb
  File "/firebase-cpp-sdk/build/external/src/firestore-build/external/src/nanopb/generator/nanopb_generator.py", line 37, in <module>
    from .proto import nanopb_pb2, plugin_pb2
ImportError: attempted relative import with no known parent package
--nanopb_out: protoc-gen-nanopb: Plugin failed with status code 1.
````

**Comment by chkuang-g** [comment] 2020-07-22 19:18
@lnjX Glad it works for you now. 

@wakely Please contact [nanopb](https://github.com/nanopb/nanopb) regarding to the issue on CentOS8

I'll close this issue for now.

**Comment by wakely** [comment] 2020-07-22 20:13
I believe nanopb has solved the problem, but you guys need to update to the latest library version.

**Comment by chkuang-g** [comment] 2020-07-25 02:12
@wakely 

That is good to know. @lnjX Could you confirm if it work after you change the nanopb version here?
https://github.com/firebase/firebase-cpp-sdk/blob/master/cmake/external/nanopb.cmake#L25

**Comment by vimanyu** [comment] 2021-04-30 00:08
Closing this as the nanopb issue was resolved sometime ago and python3 should be supported now.

**Closed by vimanyu** 2021-04-30 00:08 UTC
Labels: needs-info, type: process
