### ISSUE TITLE
Can't build AdMob for Android from source

### ISSUE THREAD

**Issue by jhasse** [firebase/firebase-cpp-sdk#225] opened 2021-01-04 21:11 UTC
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: source
  * Firebase C++ SDK version: b09efc2
  * Problematic Firebase Component: AdMob
  * Other Firebase Components in use: _____ (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Linux
  * Platform you are targeting: Android

### [REQUIRED] Please describe the issue here:

I'm trying to build from source with the latest Android Sdk and NDK 21.3.6528147, but getting the following error:

```
$ ./gradlew :admob:assembleRelease

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '11.0.9.1'.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org
```

**Comment by alexames** [comment] 2021-01-08 07:42
Appears to be a duplicate of #224

**Closed** 2021-01-08 07:42 UTC
