### ISSUE TITLE
Link error when using firestore on Win32 desktop

### ISSUE THREAD

**Issue by doandoindi** [firebase/firebase-cpp-sdk#54] opened 2020-05-06 08:37 UTC
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: website
Firebase C++ SDK version: 6.14.0
Firebase plugins in use (Auth, Database, etc.): Firestore
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Windows
Platform you are targeting (iOS, Android, and/or desktop): desktop

### Please describe the issue here:
(Please list the full steps to reproduce the issue. Include device logs, Unity logs, and stack traces if available.)

I'm trying to use the firestore in our project, unfortunately, I always get the link error when call to firestore function. For example

```
extern "C" int common_main(int argc, const char* argv[]) {
  App::Create();
  Firestore* db = Firestore::GetInstance();

  return 0;
}
```
This error is happening in both debug/release mode like bellow:
```
2>firebase_firestore.lib(8e190590a5ffbe491c9e3724aeefbb9b_fsdep_absl_time_internal_cctz_time_zone.dir_Debug_time_zone_info.obj) : error LNK2001: unresolved external symbol "class std::unique_ptr<class absl::time_internal::cctz::ZoneInfoSource,struct std::default_delete<class absl::time_internal::cctz::ZoneInfoSource> > (__cdecl* absl::time_internal::cctz_extension::zone_info_source_factory)(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::function<class std::unique_ptr<class absl::time_internal::cctz::ZoneInfoSource,struct std::default_delete<class absl::time_internal::cctz::ZoneInfoSource> > __cdecl(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)> const &)" (?zone_info_source_factory@cctz_extension@time_internal@absl@@3P6A?AV?$unique_ptr@VZoneInfoSource@cctz@time_internal@absl@@U?$default_delete@VZoneInfoSource@cctz@time_internal@absl@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@5@AEBV?$function@$$A6A?AV?$unique_ptr@VZoneInfoSource@cctz@time_internal@absl@@U?$default_delete@VZoneInfoSource@cctz@time_internal@absl@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@@Z@5@@ZEA)
2>E:\INDI\3rd\quickstart-cpp\firestore\testapp\build\Debug\desktop_testapp.exe : fatal error LNK1120: 1 unresolved externals
```
Could you take a look and show me any additional steps I need to do?

### Please answer the following, if applicable:
Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ? Yes

What's the issue repro rate? 100%

**Comment by var-const** [comment] 2020-05-07 00:00
Sorry to hear about your issue. Could you please provide some additional details about your environment?
* which version of Visual Studio are you using?
* is your build configuration 32 bit or 64 bit?
* are you building with `/MD` or `/MT`?

**Comment by doandoindi** [comment] 2020-05-07 01:42
Hello @var-const 

I'm using Visual Studio 2017 & 2019 to check for this issue. VS 2019 is using as mainly develop an environment for our product.
The above error is happening on:
- 2019 : 32 bit /MD, 32 bit /MT, 64 bit /MD. I'm getting the other link error with 64 bit /MT is `1>firebase_app.lib(8b06a1cf33ae3e301a1a0b6a784c9d54_flatbuffers.dir_Debug_idl_parser.obj) : fatal error LNK1143: invalid or corrupt file: no symbol for COMDAT section 0x615D`. To fix the COMDAT section error, we re-built the library on VS 2019, but in this check, we use the Pre-built SDK from your website, no custom at all. Do you have the plan to add the support for VS 2019?

- 2017 : 32 bit /MD, 32 bit /MT.

Let me know if you need any additional information.

**Comment by doandoindi** [comment] 2020-05-08 10:51
Hello

I'm trying to compiling the SDK with VS2019 to check if the issue still here. I have some questions, could you take your time to check them?

1. I don't find the 6.14.0 tag. Is it ok to use the master branch on head revision?
2. firebase_firestore-d.lib size is only 22MB instead of 390MB since comparing with the one I download from your website. As a result, I get a lot of linking errors when trying to use firebase_firestore lib in our application.  While checking some of them, I find it belongs to some library as (firebase_firestore_core.lib, firebase_firestore_util.lib, ...). I don't find them from CPack Packages. Is there any automation way to have them linked properly inside firebase_firestore lib?

Look forward to seeing your reply.

**Comment by OpenJeDi** [comment] 2020-05-14 13:17
I have the same issue with this unresolved absl_time_internal symbol.
I am using VS2015 64bit /MD libraries.

The previous linker errors (absl_string_internal related in 6.12) are gone though. The MacOS libraries do not have this issue: they now work fine without having to link any extra absl libraries.

The public git repository is several months old now, and the latest tag is still 6.11. Are you planning on keeping the public repository more up-to-date with development?

**Comment by jonsimantov** [comment] 2020-05-14 18:03
A few things:
1. You should be able to use the master branch at HEAD to build at any time. It may be slightly out-of-date with the most recent releases but we'll get it updated soon and are working on updating it more frequently moving forward.
2. When you build the open-source version of the SDK, you'll get much smaller libraries than the binary distribution because the dependencies (flatbuffers, grpc, absl, leveldb, etc.) will be linked in separately via cmake. So don't worry if the library size ends up much smaller, ultimately it ends up being the same total library size with all the deps.
3. The absl time_internal linker issue should be fixed in the 6.14.0 binary release. Are you seeing it in that version?

**Comment by OpenJeDi** [comment] 2020-05-14 18:06
> 3. The absl time_internal linker issue should be fixed in the 6.14.0 binary release. Are you seeing it in that version?

Yes, it is the 6.14.0 binary release. The MacOS build works fine, the windows version has the error above.

The 6.12.0 binary release had a linker error with absl_string_internal. That one is fixed in both windows and MacOS.

**Comment by jonsimantov** [comment] 2020-05-14 18:41
Thanks for the info. I believe we've found the root cause. It should be fixed in the upcoming 6.15.0 release.

**Comment by doandoindi** [comment] 2020-05-15 01:44
I'm glad to hear you found the root cause. Could you share with us when 6.15.0 will come? Are there any chances to see VS2019 supported by pre-build SDK?

**Comment by OpenJeDi** [comment] 2020-05-25 19:44
Did anyone succeed in using the precompiled 6.14.0 or 6.14.1 SDK on windows? I am unable to resolve the unresolved symbols. I tried building several versions of abseil and link the resulting absl_time* libraries, but none of them help.

**Comment by OpenJeDi** [comment] 2020-05-28 19:13
For those who are interested: I had to actually add absl/time/internal/cctz/src/zone_info_source.cc (and necessary include path) because the symbol is not exported by the abseil C++ library that I built.

**Comment by jonsimantov** [comment] 2020-05-28 19:59
The unresolved symbols on Windows will be fixed in the upcoming version of the C++ SDK, 6.15.0, which should be released soon. Sorry for the trouble!

**Comment by patm1987** [comment] 2020-06-17 20:28
Hi all!

The 6.15 SDK is out now (and pushed to this repository). Has this issue been adequately resolved?

**Comment by OpenJeDi** [comment] 2020-06-18 11:04
It works for me on both MacOS and Windows. I haven't had any issues since the release, thanks!

Good to know that the public repository was brought up to date.

**Comment by morganchen12** [comment] 2020-06-18 18:11
Thanks for the update. I'll close this issue, but feel free to comment on the closed thread if the linker errors regress.

**Closed by morganchen12** 2020-06-18 18:11 UTC
Labels: api: firestore, needs-info
