### ISSUE TITLE
FR: List files in a directory in Firebase Storage

### ISSUE THREAD

**Issue by OpenJeDi** [firebase/firebase-cpp-sdk#59] opened 2020-05-26 15:37 UTC
### Please fill in the following fields:
Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: all
Firebase C++ SDK version: latest
Firebase plugins in use (Auth, Database, etc.): storage
Additional SDKs you are using (Facebook, AdMob, etc.): 
Platform you are using the C++ SDK on (Mac, Windows, or Linux): Mac+Windows
Platform you are targeting (iOS, Android, and/or desktop): desktop

### Please describe the issue here:

Is listing of files in storage planned in the C++ SDK? I kinda assumed it would be supported already...
I will write a cloud function for now to do the listing for me.

**Comment by morganchen12** [comment] 2020-05-26 16:53
Do you mean listing files in Firebase Storage, or listing documents in Firestore?

**Comment by OpenJeDi** [comment] 2020-05-26 19:59
Ah, I mean storage. I accidentally typed firestore...

**Comment by morganchen12** [comment] 2020-05-26 23:23
From what I understand this is supported in some of the native SDKs, but currently not exposed in C++.

**Comment by chkuang-g** [comment] 2020-07-23 19:57
Duplicate of #43

**Closed by chkuang-g** 2020-07-23 19:58 UTC
Labels: api: storage, type: feature request
