### ISSUE TITLE
[Bug] Bad minSdkVersion in firebase_messaging_cpp.aar

### ISSUE THREAD

**Issue by ChristophePretty** [firebase/firebase-cpp-sdk#1510] opened 2024-01-09 10:35 UTC
### [REQUIRED] Please fill in the following fields:

  * Firebase C++ SDK version: 11.7.0
  * Problematic Firebase Component: Messaging
  * Platform you are using the C++ SDK on: Mac
  * Platform you are targeting: Android

### [REQUIRED] Please describe the issue here:

I am using Firebase Messaging from  C++ Sdk 11.7.0.
The generated Manifest add the request permissions for 
```
 <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
 <uses-permission android:name="android.permission.READ_PHONE_STATE" />
 <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
```
There were not requested in previous Sdk version and they are not needed.

It looks like there is a typo in the AndroidManifest.xml of the file firebase_messaging_cpp.aar:
The minSdkVersion is "1" (from "14" in previous version).

#### Steps to reproduce:

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ? NA
What's the issue repro rate? (eg 100%, 1/5 etc)  100%

What happened? How can we make the problem occur?

Just build an android app with Firebase Messaging C++ Sdk 11.7.0 and check the generated AndroidManifest.xml.
The permissions: READ_PHONE_STATE, WRITE_EXTERNAL_STORAGE and READ_EXTERNAL_STORAGE are present and should not be.

**Comment by jonsimantov** [comment] 2024-01-18 19:02
Thanks - I can see that the AndroidManifest.xml inside the firebase_messaging.aar did change between 11.5.0 and 11.6.0, though I'm not sure why since nothing messaging-related changed. I'll look into this.

**Comment by jonsimantov** [comment] 2024-01-18 21:29
I've tested a fix here: #1523, and I can confirm that restoring the minSdkVersion to 14 also removes the external storage requirements. If you don't want to wait for our next release, you can always try unzipping the AAR, editing the AndroidManifest.xml by hand, and then re-zipping it up. In any case, this will be fixed in the next C++ SDK release.

**Comment by ChristophePretty** [comment] 2024-01-19 09:25
Actually, it is what we did in our current version to be able to push it to production!

I'll have a look at next release, thanks.

**Comment by jonsimantov** [comment] 2024-01-19 18:39
Thanks for the bug report, and the help diagnosing!

**Closed** 2024-01-19 18:39 UTC
Labels: api: messaging, new, type: question
