### ISSUE TITLE
[Bug] Firestore Returning Snapshots For Documents That Do Not Exist

### ISSUE THREAD

**Issue by brianmichel** [firebase/firebase-cpp-sdk#1493] opened 2023-11-27 18:12 UTC
### [REQUIRED] Please fill in the following fields:

  * Pre-built SDK from the [website](https://firebase.google.com/download/cpp) or open-source from this repo: open source from this repo
  * Firebase C++ SDK version: build of commit f84253e
  * Problematic Firebase Component: Firestore (Auth, Database, etc.)
  * Other Firebase Components in use: Auth (Auth, Database, etc.)
  * Platform you are using the C++ SDK on: Windows (Mac, Windows, or Linux)
  * Platform you are targeting: Windows Desktop (iOS, Android, and/or desktop)

### [REQUIRED] Please describe the issue here:

When calling the `.Get` function on a document reference for a path that does not exist, the `is_valid()` function returns true. 

#### Steps to reproduce:

1. Setup a Firestore that has a collection called `my_documents` with a single document which has the ID `brian@cool.net`
2. Make a request to get the document `my_documents/brian@cool.net` (this should succeed)
3. Make a request to get the document `my_documents/brian@bad.net` (this should fail, but it does not)

Have you been able to reproduce this issue with just the [Firebase C++ quickstarts](https://github.com/firebase/quickstart-cpp) ?
What's the issue repro rate? (eg 100%, 1/5 etc)

I haven't tried yet, but I will now.

What happened? How can we make the problem occur?
This could be a description, log/console output, etc.

The future is returning a document in it's future for the invalid document path

If you have a downloadable sample project that reproduces the bug you're reporting, you will
likely receive a faster response on your issue.

#### Relevant Code:

Here's how we're calling the `Get` function, we're building Swift bindings to the C++ SDK so that we can use this to build our application with Swift on Windows https://github.com/thebrowsercompany/swift-firebase/blob/main/Sources/firebase/include/FirebaseFirestore.hh#L50

**Comment by brianmichel** [comment] 2023-11-27 18:14
Some screenshots of the UI in question

## Response For Invalid Document
![image](https://github.com/firebase/firebase-cpp-sdk/assets/63919/fca5d940-976c-46d3-8756-3464de182c81)

## Setup For Firestore
![CleanShot 2023-11-27 at 13 13 34@2x](https://github.com/firebase/firebase-cpp-sdk/assets/63919/9e0084b8-3ea9-4415-a80c-fb0d7d3ff7c4)

**Comment by milaGGL** [comment] 2023-11-27 19:02
Hi @brianmichel, thank you for reporting this issue. Could you please provide a code snippet you used? 

By design, when calling get on a doc path that doesn't exist, Firestore should return an empty snapshot, not an error.  Calling `exists` on it will return `false` as the document doesn't exist: https://github.com/firebase/firebase-cpp-sdk/blob/42b57ecd524641c717c9bb3dca658b6697b0b4dd/firestore/src/include/firebase/firestore/document_snapshot.h#L172

while `is_valid` is focused on the validation of a  'DocumentSnapshot` instance itself:  https://github.com/firebase/firebase-cpp-sdk/blob/42b57ecd524641c717c9bb3dca658b6697b0b4dd/firestore/src/include/firebase/firestore/document_snapshot.h#L243

**Comment by brianmichel** [comment] 2023-11-27 19:15
> Hi @brianmichel, thank you for reporting this issue. Could you please provide a code snippet you used?
> 
> By design, when calling get on a doc path that doesn't exist, Firestore should return an empty snapshot, not an error. Calling `exists` on it will return `false` as the document doesn't exist:
> 
> https://github.com/firebase/firebase-cpp-sdk/blob/42b57ecd524641c717c9bb3dca658b6697b0b4dd/firestore/src/include/firebase/firestore/document_snapshot.h#L172
> 
> while `is_valid` is focused on the validation of a 'DocumentSnapshot` instance itself:
> 
> https://github.com/firebase/firebase-cpp-sdk/blob/42b57ecd524641c717c9bb3dca658b6697b0b4dd/firestore/src/include/firebase/firestore/document_snapshot.h#L243

Thanks for the quick reply @milaGGL here's the [code](https://github.com/thebrowsercompany/swift-firebase/blob/5cef2f98647551983ef74131cc7192d77b234d02/Sources/firebase/include/FirebaseFirestore.hh#L46-L51) we use to generate the future:
```c++
inline ::firebase::Future<::firebase::firestore::DocumentSnapshot>
document_get(const ::firebase::firestore::DocumentReference document,
             ::firebase::firestore::Source source =
                 ::firebase::firestore::Source::kDefault) {
  return document.Get(source);
}
```

And [here](https://github.com/thebrowsercompany/swift-firebase/blob/5cef2f98647551983ef74131cc7192d77b234d02/Sources/FirebaseFirestore/DocumentReference%2BSwift.swift#L32-L52) is the Swift bridging code that waits for the Future and tries to see if there's a document to return:

```swift
  public func get() async throws -> DocumentSnapshot? {
    typealias Promise = CheckedContinuation<UnsafeMutablePointer<firebase.firestore.DocumentSnapshot>, any Error>
    let snapshot = try await withCheckedThrowingContinuation { (continuation: Promise) in
      let future = swift_firebase.swift_cxx_shims.firebase.firestore.document_get(self, .default)
      withUnsafePointer(to: continuation) { continuation in
        future.OnCompletion_SwiftWorkaround({ future, pvContinuation in
          let pContinuation = pvContinuation?.assumingMemoryBound(to: Promise.self)
          if future.pointee.error() == 0 {
            pContinuation.pointee.resume(returning: .init(mutating: future.pointee.__resultUnsafe()))
          } else {
            let code = future.pointee.error()
            let message = String(cString: future.pointee.__error_messageUnsafe()!)
            pContinuation.pointee.resume(throwing: FirebaseError(code: code, message: message))
          }
        }, UnsafeMutableRawPointer(mutating: continuation))
      }
      future.Wait(firebase.FutureBase.kWaitTimeoutInfinite)
    }

    return snapshot.pointee.is_valid() ? snapshot.pointee : nil
  }
```

I'm going to guess we need to change out `snapshot.pointee.is_valid()` to `snapshot.pointee.exists`?

**Comment by wu-hui** [comment] 2024-02-09 20:01
@jonsimantov Can we close this one? I don't have the permission it appears.

**Closed** 2024-02-11 02:53 UTC
Labels: api: firestore, new, type: question
